#!/bin/sh

# 15-Sep-2026: Clear environment before relaunching MSC.app
#              in response to https://github.com/munki/munki/issues/1395
# 15-Sep-2026: Drop support for older launchctl bsexec method needed for
#              macOS 10.10 and earlier

export PATH=/usr/bin:/bin:/usr/sbin:/sbin

# relaunch MSC.app if it was running before we upgraded it
MSC_APP="/Applications/Managed Software Center.app"

if [ "$3" == "/" ]; then
    if [ -e /tmp/com.googlecode.munki.relaunch_msc_app ] ; then
        FRONTMOST=$(cat /tmp/com.googlecode.munki.relaunch_msc_app)
        rm /tmp/com.googlecode.munki.relaunch_msc_app
        if [ "$FRONTMOST" == "frontmost" ] ; then
            OPENCMD="/usr/bin/open -a"
        else
            OPENCMD="/usr/bin/open -g -a"
        fi
        CONSOLEUSER=$(who | grep console | cut -d" " -f1)
        if [ "$CONSOLEUSER" == "" ] ; then
            exit 0
        fi
        CONSOLE_UID=$(id -u "$CONSOLEUSER")
        for uid in $(ps -axo uid,args | grep -i "[l]oginwindow.app" | awk '{print $1}'); do
            if [ "$uid" == "$CONSOLE_UID" ] ; then
                # use '/usr/bin/env -i' so the launched process does not inherit
                # root's HOME and TMPDIR (and other things in root's ENV)
                launchctl asuser "$uid" /usr/bin/env -i $OPENCMD "$MSC_APP"
                exit 0
            fi
        done
    fi
fi
