#!/usr/local/munki/Python.framework/Versions/Current/bin/python3

import sys
sys.path.append("/usr/local/munki")
from munkilib import launchd

job = launchd.Job(
    ["/usr/local/munki/managedsoftwareupdate", "--auto"], cleanup_at_exit=False)
job.start()
