#!/bin/sh

# use launchctl to submit a job to run managedsoftwareupdate
# so that the script returns before the job finishes and ending
# the installer taks does not end the managedsoftwareupdate run
# (It's quite possible that `/usr/local/munki/managedsoftwareupdate --auto &`
# would work as well!)

/bin/launchctl submit -l com.googlecode.munki.autorun -- /usr/local/munki/managedsoftwareupdate --auto