// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "munki-tools",
    platforms: [.macOS(.v13)],
    dependencies: [
        .package(url: "https://github.com/apple/swift-argument-parser.git", from: "1.5.0"),
        .package(url: "https://github.com/apple/swift-crypto.git", from: "3.0.0"),
        .package(url: "https://github.com/jpsim/Yams.git", from: "6.0.2"),
    ],
    targets: [
        .executableTarget(
            name: "makecatalogs",
            dependencies: [
                .product(name: "ArgumentParser", package: "swift-argument-parser"),
                .product(name: "Crypto", package: "swift-crypto", condition: .when(platforms: [.linux])),
                .product(name: "Yams", package: "Yams"),
            ],
            path: ".",
            exclude: [
                "app_usage_monitor",
                "appusaged",
                "authrestartd",
                "iconimporter",
                "installhelper",
                "launchapp",
                "logouthelper",
                "makecatalogs/makecatalogs.entitlements",
                "makepkginfo",
                "managedsoftwareupdate",
                "manifestutil",
                "munkiCLItesting",
                "munkiimport",
                "munkitester",
                "precache_agent",
                "removepackages",
                "repocheck",
                "repoclean",
                "shared/admin/configure.swift",
                "shared/admin/munkiimportlib.swift",
                "shared/admin/munkiimportOptions.swift",
                "shared/admin/pkginfolib.swift",
                "shared/admin/pkginfoOptions.swift",
                "shared/admin/readline.swift",
                "shared/appinventory.swift",
                "shared/appleupdates.swift",
                "shared/appusage.swift",
                "shared/authrestart.swift",
                "shared/authrestartclient.swift",
                "shared/BlockingApplications.swift",
                "shared/bootstrapping.swift",
                "shared/display.swift",
                "shared/facts.swift",
                "shared/headers",
                "shared/info.swift",
                "shared/installer",
                "shared/installinfo.swift",
                "shared/keychain.swift",
                "shared/launchd.swift",
                "shared/LaunchdJob.swift",
                "shared/munkilog.swift",
                "shared/munkistatus.swift",
                "shared/network",
                "shared/osinstaller",
                "shared/PosixSpawn.swift",
                "shared/powermanager.swift",
                "shared/Predicates.m",
                "shared/prefs.swift",
                "shared/processes.swift",
                "shared/reports.swift",
                "shared/SignalHandler.swift",
                "shared/socket",
                "shared/sqlite3.swift",
                "shared/stoprequested.swift",
                "shared/UNIXProcessInfo.swift",
                "shared/updatecheck",
                "shared/utils/dateutils.swift",
                "shared/utils/dmgutils.swift",
                "shared/utils/iconutils.swift",
                "shared/utils/ODutils.swift",
                "shared/utils/osutils.swift",
                "shared/utils/pkgutils.swift",
                "shared/utils/scriptutils.swift",
                "shared/utils/tempfileutils.swift",
                "shared/utils/versionutils.swift",
                "shared/xattr.swift",
                "Package.resolved",
            ],
            sources: [
                "makecatalogs/makecatalogs.swift",
                "shared/admin/makecatalogslib.swift",
                "shared/admin/admincommon.swift",
                "shared/munkirepo/RepoProtocol.swift",
                "shared/munkirepo/FileRepo.swift",
                "shared/munkirepo/GitFileRepo.swift",
                "shared/munkirepo/RepoFactory.swift",
                "shared/munkirepo/repoutils.swift",
                "shared/utils/plistutils.swift",
                "shared/utils/yamlutils.swift",
                "shared/utils/cliutils.swift",
                "shared/utils/fileutils.swift",
                "shared/utils/stderrout.swift",
                "shared/utils/stringutils.swift",
                "shared/utils/dictutils.swift",
                "shared/munkihash.swift",
                "shared/version.swift",
                "shared/constants.swift",
                "shared/errors.swift",
            ]
        ),
    ]
)
